

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    
    <title>8. Erros e exceções &mdash; Python v2.7.2 documentation</title>
    <link rel="stylesheet" href="../_static/default.css" type="text/css" />
    <link rel="stylesheet" href="../_static/pygments.css" type="text/css" />
    <script type="text/javascript">
      var DOCUMENTATION_OPTIONS = {
        URL_ROOT:    '../',
        VERSION:     '2.7.2',
        COLLAPSE_INDEX: false,
        FILE_SUFFIX: '.html',
        HAS_SOURCE:  true
      };
    </script>
    <script type="text/javascript" src="../_static/jquery.js"></script>
    <script type="text/javascript" src="../_static/underscore.js"></script>
    <script type="text/javascript" src="../_static/doctools.js"></script>
    <link rel="search" type="application/opensearchdescription+xml"
          title="Search within Python v2.7.2 documentation"
          href="../_static/opensearch.xml"/>
    <link rel="author" title="About these documents" href="../about.html" />
    <link rel="copyright" title="Copyright" href="../copyright.html" />
    <link rel="top" title="Python v2.7.2 documentation" href="../index.html" />
    <link rel="up" title="O tutorial de Python" href="index.html" />
    <link rel="next" title="9. Classes" href="classes.html" />
    <link rel="prev" title="7. Entrada e saída" href="inputoutput.html" />
    <link rel="shortcut icon" type="image/png" href="../_static/py.png" />
    <script type="text/javascript" src="../_static/copybutton.js"></script>
 

  </head>
  <body>
    <div class="related">
      <h3>Navigation</h3>
      <ul>
        <li class="right" style="margin-right: 10px">
          <a href="../genindex.html" title="General Index"
             accesskey="I">index</a></li>
        <li class="right" >
          <a href="../py-modindex.html" title="Python Module Index"
             >modules</a> |</li>
        <li class="right" >
          <a href="classes.html" title="9. Classes"
             accesskey="N">next</a> |</li>
        <li class="right" >
          <a href="inputoutput.html" title="7. Entrada e saída"
             accesskey="P">previous</a> |</li>
        <li><img src="../_static/py.png" alt=""
                 style="vertical-align: middle; margin-top: -1px"/></li>
        <li><a href="../index.html">Python v2.7.2 documentation</a> &raquo;</li>

          <li><a href="index.html" accesskey="U">O tutorial de Python</a> &raquo;</li> 
      </ul>
    </div>  

    <div class="document">
      <div class="documentwrapper">
        <div class="bodywrapper">
          <div class="body">
            
  <div class="section" id="erros-e-excecoes">
<span id="tut-errors"></span><h1>8. Erros e exceções<a class="headerlink" href="#erros-e-excecoes" title="Permalink to this headline">¶</a></h1>
<p>Até agora mensagens de erro foram apenas mencionadas, mas se você testou os
exemplos, talvez tenha esbarrado em algumas. Existem pelo menos dois tipos
distintos de  erros: <em>erros de sintaxe</em> e <em>exceções</em>.</p>
<div class="section" id="erros-de-sintaxe">
<span id="tut-syntaxerrors"></span><h2>8.1. Erros de sintaxe<a class="headerlink" href="#erros-de-sintaxe" title="Permalink to this headline">¶</a></h2>
<p>Erros de sintaxe, também conhecidos como erros de parse, são provavelmente os
mais frequentes entre aqueles que ainda estão aprendendo Python:</p>
<div class="highlight-python"><div class="highlight"><pre><span class="gp">&gt;&gt;&gt; </span><span class="k">while</span> <span class="bp">True</span> <span class="k">print</span> <span class="s">&#39;Olá mundo&#39;</span>
<span class="go">  File &quot;&lt;stdin&gt;&quot;, line 1, in ?</span>
<span class="go">    while True print &#39;Olá mundo&#39;</span>
<span class="go">                   ^</span>
<span class="go">SyntaxError: invalid syntax</span>
</pre></div>
</div>
<p>O parser repete a linha inválida e apresenta uma pequena &#8216;seta&#8217; apontando para
o ponto da linha em que o erro foi encontrado. O erro é causado (ou ao menos
detectado) pelo token que <em>precede</em> a seta: no exemplo, o erro foi detectado
na palavra reservada <a class="reference internal" href="../reference/simple_stmts.html#print"><tt class="xref std std-keyword docutils literal"><span class="pre">print</span></tt></a>, uma vez que o dois-pontos (<tt class="docutils literal"><span class="pre">':'</span></tt>)
está faltando antes dela. O nome de arquivo e número de linha são exibidos
para que você possa rastrear o erro no texto do script.</p>
</div>
<div class="section" id="excecoes">
<span id="tut-exceptions"></span><h2>8.2. Exceções<a class="headerlink" href="#excecoes" title="Permalink to this headline">¶</a></h2>
<p>Mesmo que um comando ou expressão estejam sintaticamente corretos, talvez
ocorra um erro na hora de sua execução. Erros detectados durante a execução
são chamados <em>exceções</em> e não são necessariamente fatais: logo veremos como
tratá-las em programas Python. A maioria das exceções não são tratadas e
acabam resultando em mensagens de erro:</p>
<div class="highlight-python"><div class="highlight"><pre><span class="gp">&gt;&gt;&gt; </span><span class="mi">10</span> <span class="o">*</span> <span class="p">(</span><span class="mi">1</span><span class="o">/</span><span class="mi">0</span><span class="p">)</span>
<span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;&lt;stdin&gt;&quot;</span>, line <span class="m">1</span>, in <span class="n-Identifier">?</span>
<span class="nc">ZeroDivisionError</span>: <span class="n-Identifier">integer division or modulo by zero</span>
<span class="gp">&gt;&gt;&gt; </span><span class="mi">4</span> <span class="o">+</span> <span class="n">spam</span><span class="o">*</span><span class="mi">3</span>
<span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;&lt;stdin&gt;&quot;</span>, line <span class="m">1</span>, in <span class="n-Identifier">?</span>
<span class="nc">NameError</span>: <span class="n-Identifier">name &#39;spam&#39; is not defined</span>
<span class="gp">&gt;&gt;&gt; </span><span class="s">&#39;2&#39;</span> <span class="o">+</span> <span class="mi">2</span>
<span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;&lt;stdin&gt;&quot;</span>, line <span class="m">1</span>, in <span class="n-Identifier">?</span>
<span class="nc">TypeError</span>: <span class="n-Identifier">cannot concatenate &#39;str&#39; and &#39;int&#39; objects</span>
</pre></div>
</div>
<p>A última linha da mensagem de erro indica o que aconteceu. Exceções surgem com
diferentes tipos, e o tipo é exibido como parte da mensagem: os tipos no
exemplo são <a class="reference internal" href="../library/exceptions.html#exceptions.ZeroDivisionError" title="exceptions.ZeroDivisionError"><tt class="xref py py-exc docutils literal"><span class="pre">ZeroDivisionError</span></tt></a>, <a class="reference internal" href="../library/exceptions.html#exceptions.NameError" title="exceptions.NameError"><tt class="xref py py-exc docutils literal"><span class="pre">NameError</span></tt></a> e <a class="reference internal" href="../library/exceptions.html#exceptions.TypeError" title="exceptions.TypeError"><tt class="xref py py-exc docutils literal"><span class="pre">TypeError</span></tt></a>. A
string exibida como sendo o tipo da exceção é o nome interno da exceção que
ocorreu. Isso é verdade para todas exceções pré-definidas em Python, mas não é
necessariamente verdade para exceções definidas pelo usuário (embora seja uma
convenção útil). Os nomes das exceções padrões são identificadores embutidos
(não palavras reservadas).</p>
<p>O resto da linha é um detalhamento que depende do tipo da exceção ocorrida e
sua causa.</p>
<p>A parte anterior da mensagem de erro apresenta o contexto onde ocorreu a
exceção. Essa informação é denominada <em>stack traceback</em> (situação da pilha de
execução). Em geral, contém uma lista de linhas do código fonte, sem
apresentar, no entanto, linhas lidas da entrada padrão.</p>
<p><a class="reference internal" href="../library/exceptions.html#bltin-exceptions"><em>Built-in Exceptions</em></a> lista as exceções pré-definidas e seus significados.</p>
</div>
<div class="section" id="tratamento-de-excecoes">
<span id="tut-handling"></span><h2>8.3. Tratamento de exceções<a class="headerlink" href="#tratamento-de-excecoes" title="Permalink to this headline">¶</a></h2>
<p>É possível escrever programas que tratam exceções específicas. Observe o
exemplo seguinte, que pede dados ao usuário até que um inteiro válido seja
fornecido, ainda permitindo que o programa seja interrompido (utilizando
<tt class="kbd docutils literal"><span class="pre">Control-C</span></tt> ou seja lá o que for que o sistema operacional suporte); note
que uma interrupção gerada pelo usuário será sinalizada pela exceção
<a class="reference internal" href="../library/exceptions.html#exceptions.KeyboardInterrupt" title="exceptions.KeyboardInterrupt"><tt class="xref py py-exc docutils literal"><span class="pre">KeyboardInterrupt</span></tt></a>.</p>
<div class="highlight-python"><div class="highlight"><pre><span class="gp">&gt;&gt;&gt; </span><span class="k">while</span> <span class="bp">True</span><span class="p">:</span>
<span class="gp">... </span>    <span class="k">try</span><span class="p">:</span>
<span class="gp">... </span>        <span class="n">x</span> <span class="o">=</span> <span class="nb">int</span><span class="p">(</span><span class="nb">raw_input</span><span class="p">(</span><span class="s">&quot;Por favor, informe um número: &quot;</span><span class="p">))</span>
<span class="gp">... </span>        <span class="k">break</span>
<span class="gp">... </span>    <span class="k">except</span> <span class="ne">ValueError</span><span class="p">:</span>
<span class="gp">... </span>        <span class="k">print</span> <span class="s">&quot;Oops!  Não foi um número válido.  Tente novamente...&quot;</span>
<span class="gp">...</span>
</pre></div>
</div>
<p>A instrução <a class="reference internal" href="../reference/compound_stmts.html#try"><tt class="xref std std-keyword docutils literal"><span class="pre">try</span></tt></a> funciona da seguinte maneira:</p>
<ul class="simple">
<li>Primeiramente, a <em>cláusula try</em> (o conjunto de instruções entre as palavras
reservadas <a class="reference internal" href="../reference/compound_stmts.html#try"><tt class="xref std std-keyword docutils literal"><span class="pre">try</span></tt></a> e <a class="reference internal" href="../reference/compound_stmts.html#except"><tt class="xref std std-keyword docutils literal"><span class="pre">except</span></tt></a> ) é executada.</li>
<li>Se nenhuma exceção ocorrer, a <em>cláusula except</em> é ignorada e a execução da
instrução <a class="reference internal" href="../reference/compound_stmts.html#try"><tt class="xref std std-keyword docutils literal"><span class="pre">try</span></tt></a> é finalizada.</li>
<li>Se ocorrer uma execução durante a execução da cláusula try, as instruções
remanescentes na cláusula são ignoradas. Se o tipo da exceção ocorrida tiver
sido previsto em algum <a class="reference internal" href="../reference/compound_stmts.html#except"><tt class="xref std std-keyword docutils literal"><span class="pre">except</span></tt></a>, então essa cláusula será
executada. Depois disso, a execução continua na próxima instrução após
o conjunto <em>try/except</em>.</li>
<li>Se a exceção levantada não foi prevista em nenhuma cláusula
<a class="reference internal" href="../reference/compound_stmts.html#except"><tt class="xref std std-keyword docutils literal"><span class="pre">except</span></tt></a> da cláusula <a class="reference internal" href="../reference/compound_stmts.html#try"><tt class="xref std std-keyword docutils literal"><span class="pre">try</span></tt></a> em que ocorreu, então ela é
entregue a uma instrução <a class="reference internal" href="../reference/compound_stmts.html#try"><tt class="xref std std-keyword docutils literal"><span class="pre">try</span></tt></a> mais externa. Se não existir nenhum
tratador previsto para tal exceção, será uma <em>exceção não tratada</em> e a
execução do programa termina com uma mensagem de erro.</li>
</ul>
<p>A instrução <a class="reference internal" href="../reference/compound_stmts.html#try"><tt class="xref std std-keyword docutils literal"><span class="pre">try</span></tt></a> pode ter mais de uma cláusula <a class="reference internal" href="../reference/compound_stmts.html#except"><tt class="xref std std-keyword docutils literal"><span class="pre">except</span></tt></a>
para especificar múltiplos tratadores para diferentes exceções. No máximo um
único tratador será ativado. Tratadores só são sensíveis às exceções
levantadas no interior da cláusula try, e não às que tenham ocorrido no
interior de outro tratador numa mesma instrução <a class="reference internal" href="../reference/compound_stmts.html#try"><tt class="xref std std-keyword docutils literal"><span class="pre">try</span></tt></a>. Um tratador
pode ser sensível a múltiplas exceções, desde que as especifique em uma
tupla:</p>
<div class="highlight-python"><div class="highlight"><pre><span class="o">...</span> <span class="k">except</span> <span class="p">(</span><span class="ne">RuntimeError</span><span class="p">,</span> <span class="ne">TypeError</span><span class="p">,</span> <span class="ne">NameError</span><span class="p">):</span>
<span class="o">...</span>     <span class="k">pass</span>
</pre></div>
</div>
<p>A última cláusula <a class="reference internal" href="../reference/compound_stmts.html#except"><tt class="xref std std-keyword docutils literal"><span class="pre">except</span></tt></a> pode omitir o nome da exceção, funcionando
como um curinga. Utilize esse recurso com extrema cautela, uma vez que isso
pode esconder erros do programador e do usuário! Também pode ser utilizado
para exibir uma mensagem de erro e então re-levantar a exceção (permitindo que
o invocador da função atual também possa tratá-la).</p>
<div class="highlight-python"><div class="highlight"><pre><span class="kn">import</span> <span class="nn">sys</span>

<span class="k">try</span><span class="p">:</span>
    <span class="n">f</span> <span class="o">=</span> <span class="nb">open</span><span class="p">(</span><span class="s">&#39;meuarquivo.txt&#39;</span><span class="p">)</span>
    <span class="n">s</span> <span class="o">=</span> <span class="n">f</span><span class="o">.</span><span class="n">readline</span><span class="p">()</span>
    <span class="n">i</span> <span class="o">=</span> <span class="nb">int</span><span class="p">(</span><span class="n">s</span><span class="o">.</span><span class="n">strip</span><span class="p">())</span>
<span class="k">except</span> <span class="ne">IOError</span> <span class="k">as</span> <span class="p">(</span><span class="n">errno</span><span class="p">,</span> <span class="n">strerror</span><span class="p">):</span>
    <span class="k">print</span> <span class="s">&quot;I/O error({0}): {1}&quot;</span><span class="o">.</span><span class="n">format</span><span class="p">(</span><span class="n">errno</span><span class="p">,</span> <span class="n">strerror</span><span class="p">)</span>
<span class="k">except</span> <span class="ne">ValueError</span><span class="p">:</span>
    <span class="k">print</span> <span class="s">&quot;Não foi possível converter o dado para inteiro.&quot;</span>
<span class="k">except</span><span class="p">:</span>
    <span class="k">print</span> <span class="s">&quot;Erro inesperado:&quot;</span><span class="p">,</span> <span class="n">sys</span><span class="o">.</span><span class="n">exc_info</span><span class="p">()[</span><span class="mi">0</span><span class="p">]</span>
    <span class="k">raise</span>
</pre></div>
</div>
<p>A construção <a class="reference internal" href="../reference/compound_stmts.html#try"><tt class="xref std std-keyword docutils literal"><span class="pre">try</span></tt></a> ... <a class="reference internal" href="../reference/compound_stmts.html#except"><tt class="xref std std-keyword docutils literal"><span class="pre">except</span></tt></a> possui uma <em>cláusula else</em>
opcional, que quando presente, deve ser colocada depois de todas as outras
cláusulas. É útil para um código que precisa ser executado se nenhuma exceção
foi levantada. Por exemplo:</p>
<div class="highlight-python"><div class="highlight"><pre><span class="k">for</span> <span class="n">arg</span> <span class="ow">in</span> <span class="n">sys</span><span class="o">.</span><span class="n">argv</span><span class="p">[</span><span class="mi">1</span><span class="p">:]:</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="n">f</span> <span class="o">=</span> <span class="nb">open</span><span class="p">(</span><span class="n">arg</span><span class="p">,</span> <span class="s">&#39;r&#39;</span><span class="p">)</span>
    <span class="k">except</span> <span class="ne">IOError</span><span class="p">:</span>
        <span class="k">print</span> <span class="s">&#39;não foi possível abrir&#39;</span><span class="p">,</span> <span class="n">arg</span>
    <span class="k">else</span><span class="p">:</span>
        <span class="k">print</span> <span class="n">arg</span><span class="p">,</span> <span class="s">&#39;tem&#39;</span><span class="p">,</span> <span class="nb">len</span><span class="p">(</span><span class="n">f</span><span class="o">.</span><span class="n">readlines</span><span class="p">()),</span> <span class="s">&#39;linhas&#39;</span>
        <span class="n">f</span><span class="o">.</span><span class="n">close</span><span class="p">()</span>
</pre></div>
</div>
<p>Esse recurso é melhor do que simplesmente adicionar o código da cláusula
<a class="reference internal" href="../reference/compound_stmts.html#else"><tt class="xref std std-keyword docutils literal"><span class="pre">else</span></tt></a> ao corpo da cláusula <a class="reference internal" href="../reference/compound_stmts.html#try"><tt class="xref std std-keyword docutils literal"><span class="pre">try</span></tt></a>, pois mantém as exceções
levantadas no <a class="reference internal" href="../reference/compound_stmts.html#else"><tt class="xref std std-keyword docutils literal"><span class="pre">else</span></tt></a> num escopo diferente de tratamento das exceções
levantadas na cláusula <a class="reference internal" href="../reference/compound_stmts.html#try"><tt class="xref std std-keyword docutils literal"><span class="pre">try</span></tt></a>, evitando que acidentalmente seja
tratada uma exceção que não foi levantada pelo código protegido pela
construção  <a class="reference internal" href="../reference/compound_stmts.html#try"><tt class="xref std std-keyword docutils literal"><span class="pre">try</span></tt></a> ... <a class="reference internal" href="../reference/compound_stmts.html#except"><tt class="xref std std-keyword docutils literal"><span class="pre">except</span></tt></a>.</p>
<p>Quando uma exceção ocorre, ela pode estar associada a um valor chamado
<em>argumento</em> da exceção. A presença e o tipo do argumento dependem do tipo da
exceção.</p>
<p>A cláusula except pode especificar uma variável depois do nome (ou da tupla de
nomes) da exceção. A variável é associada à instância de exceção capturada,
com os argumentos armazenados em <tt class="docutils literal"><span class="pre">instancia.args</span></tt>. Por conveniência, a
instância define o método <a class="reference internal" href="../reference/datamodel.html#object.__str__" title="object.__str__"><tt class="xref py py-meth docutils literal"><span class="pre">__str__()</span></tt></a> para que os argumentos possam ser
exibidos diretamente sem necessidade de acessar <tt class="docutils literal"><span class="pre">.args</span></tt>.</p>
<p>Pode-se também instanciar uma exceção antes de levantá-la e adicionar qualquer
atributo a ela, conforme desejado.</p>
<div class="highlight-python"><div class="highlight"><pre><span class="gp">&gt;&gt;&gt; </span><span class="k">try</span><span class="p">:</span>
<span class="gp">... </span>   <span class="k">raise</span> <span class="ne">Exception</span><span class="p">(</span><span class="s">&#39;spam&#39;</span><span class="p">,</span> <span class="s">&#39;eggs&#39;</span><span class="p">)</span>
<span class="gp">... </span><span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">inst</span><span class="p">:</span>
<span class="gp">... </span>   <span class="k">print</span> <span class="nb">type</span><span class="p">(</span><span class="n">inst</span><span class="p">)</span> <span class="c"># a instância da exceção</span>
<span class="gp">... </span>   <span class="k">print</span> <span class="n">inst</span><span class="o">.</span><span class="n">args</span>  <span class="c"># argumentos armazenados em .args</span>
<span class="gp">... </span>   <span class="k">print</span> <span class="n">inst</span>       <span class="c"># __str__ permite exibir args diretamente</span>
<span class="gp">... </span>   <span class="n">x</span><span class="p">,</span> <span class="n">y</span> <span class="o">=</span> <span class="n">inst</span>      <span class="c"># __getitem__ permite desempacotar args diretamente</span>
<span class="gp">... </span>   <span class="k">print</span> <span class="s">&#39;x =&#39;</span><span class="p">,</span> <span class="n">x</span>
<span class="gp">... </span>   <span class="k">print</span> <span class="s">&#39;y =&#39;</span><span class="p">,</span> <span class="n">y</span>
<span class="gp">...</span>
<span class="go">&lt;type &#39;exceptions.Exception&#39;&gt;</span>
<span class="go">(&#39;spam&#39;, &#39;eggs&#39;)</span>
<span class="go">(&#39;spam&#39;, &#39;eggs&#39;)</span>
<span class="go">x = spam</span>
<span class="go">y = eggs</span>
</pre></div>
</div>
<p>Se uma exceção possui argumento, ele é exibido ao final (&#8216;detalhe&#8217;) da
mensagem de exceções não tratadas.</p>
<p>Além disso, tratadores de exceção são capazes de capturar exceções que tenham
sido levantadas no interior de funções invocadas (mesmo que indiretamente) na
cláusula try. Por exemplo:</p>
<div class="highlight-python"><div class="highlight"><pre><span class="gp">&gt;&gt;&gt; </span><span class="k">def</span> <span class="nf">isso_falha</span><span class="p">():</span>
<span class="gp">... </span>    <span class="n">x</span> <span class="o">=</span> <span class="mi">1</span><span class="o">/</span><span class="mi">0</span>
<span class="gp">...</span>
<span class="gp">&gt;&gt;&gt; </span><span class="k">try</span><span class="p">:</span>
<span class="gp">... </span>    <span class="n">isso_falha</span><span class="p">()</span>
<span class="gp">... </span><span class="k">except</span> <span class="ne">ZeroDivisionError</span> <span class="k">as</span> <span class="n">detalhe</span><span class="p">:</span>
<span class="gp">... </span>    <span class="k">print</span> <span class="s">&#39;Tratando erros em tempo de execução:&#39;</span><span class="p">,</span> <span class="n">detalhe</span>
<span class="gp">...</span>
<span class="go">Tratando erros em tempo de execução: integer division or modulo by zero</span>
</pre></div>
</div>
</div>
<div class="section" id="levantando-excecoes">
<span id="tut-raising"></span><h2>8.4. Levantando exceções<a class="headerlink" href="#levantando-excecoes" title="Permalink to this headline">¶</a></h2>
<p>A instrução <a class="reference internal" href="../reference/simple_stmts.html#raise"><tt class="xref std std-keyword docutils literal"><span class="pre">raise</span></tt></a> permite ao programador forçar a ocorrência de um
determinado tipo de exceção. Por exemplo:</p>
<div class="highlight-python"><div class="highlight"><pre><span class="gp">&gt;&gt;&gt; </span><span class="k">raise</span> <span class="ne">NameError</span><span class="p">(</span><span class="s">&#39;HiThere&#39;</span><span class="p">)</span>
<span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;&lt;stdin&gt;&quot;</span>, line <span class="m">1</span>, in <span class="n-Identifier">?</span>
<span class="nc">NameError</span>: <span class="n-Identifier">HiThere</span>
</pre></div>
</div>
<p>O argumento de <a class="reference internal" href="../reference/simple_stmts.html#raise"><tt class="xref std std-keyword docutils literal"><span class="pre">raise</span></tt></a> indica a exceção a ser levantada. Esse
argumento deve ser uma instância de exceção ou uma classe de exceção (uma
classe que deriva de <tt class="xref py py-class docutils literal"><span class="pre">Exception</span></tt>)</p>
<p>Caso você precise determinar se uma exceção foi levantada ou não, mas não quer
manipular o erro, uma forma simples de instrução <a class="reference internal" href="../reference/simple_stmts.html#raise"><tt class="xref std std-keyword docutils literal"><span class="pre">raise</span></tt></a> permite que
você levante-a novamente:</p>
<div class="highlight-python"><div class="highlight"><pre><span class="gp">&gt;&gt;&gt; </span><span class="k">try</span><span class="p">:</span>
<span class="gp">... </span>    <span class="k">raise</span> <span class="ne">NameError</span><span class="p">(</span><span class="s">&#39;HiThere&#39;</span><span class="p">)</span>
<span class="gp">... </span><span class="k">except</span> <span class="ne">NameError</span><span class="p">:</span>
<span class="gp">... </span>    <span class="k">print</span> <span class="s">&#39;Uma exceção voou!&#39;</span>
<span class="gp">... </span>    <span class="k">raise</span>
<span class="gp">...</span>
<span class="go">Uma exceção voou!</span>
<span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;&lt;stdin&gt;&quot;</span>, line <span class="m">2</span>, in <span class="n-Identifier">?</span>
<span class="nc">NameError</span>: <span class="n-Identifier">HiThere</span>
</pre></div>
</div>
</div>
<div class="section" id="excecoes-definidas-pelo-usuario">
<span id="tut-userexceptions"></span><h2>8.5. Exceções definidas pelo usuário<a class="headerlink" href="#excecoes-definidas-pelo-usuario" title="Permalink to this headline">¶</a></h2>
<p>Programas podem definir novos tipos de exceções, através da criação de uma
nova classe (veja <a class="reference internal" href="classes.html#tut-classes"><em>Classes</em></a> para mais informações sobre classes
Python). Exceções devem ser derivadas da classe <a class="reference internal" href="../library/exceptions.html#exceptions.Exception" title="exceptions.Exception"><tt class="xref py py-exc docutils literal"><span class="pre">Exception</span></tt></a>, direta ou
indiretamente. Por exemplo:</p>
<div class="highlight-python"><div class="highlight"><pre><span class="gp">&gt;&gt;&gt; </span><span class="k">class</span> <span class="nc">MeuErro</span><span class="p">(</span><span class="ne">Exception</span><span class="p">):</span>
<span class="gp">... </span>    <span class="k">def</span> <span class="nf">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">valor</span><span class="p">):</span>
<span class="gp">... </span>        <span class="bp">self</span><span class="o">.</span><span class="n">valor</span> <span class="o">=</span> <span class="n">valor</span>
<span class="gp">... </span>    <span class="k">def</span> <span class="nf">__str__</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
<span class="gp">... </span>        <span class="k">return</span> <span class="nb">repr</span><span class="p">(</span><span class="bp">self</span><span class="o">.</span><span class="n">valor</span><span class="p">)</span>
<span class="gp">...</span>
<span class="gp">&gt;&gt;&gt; </span><span class="k">try</span><span class="p">:</span>
<span class="gp">... </span>    <span class="k">raise</span> <span class="n">MeuErro</span><span class="p">(</span><span class="mi">2</span><span class="o">*</span><span class="mi">2</span><span class="p">)</span>
<span class="gp">... </span><span class="k">except</span> <span class="n">MeuErro</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
<span class="gp">... </span>    <span class="k">print</span> <span class="s">&#39;Minha exceção ocorreu, valor:&#39;</span><span class="p">,</span> <span class="n">e</span><span class="o">.</span><span class="n">valor</span>
<span class="gp">...</span>
<span class="go">Minha exceção ocorreu, valor: 4</span>
<span class="gp">&gt;&gt;&gt; </span><span class="k">raise</span> <span class="n">MeuErro</span><span class="p">(</span><span class="s">&#39;oops!&#39;</span><span class="p">)</span>
<span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;&lt;stdin&gt;&quot;</span>, line <span class="m">1</span>, in <span class="n-Identifier">?</span>
<span class="nc">__main__.MeuErro</span>: <span class="n-Identifier">&#39;oops!&#39;</span>
</pre></div>
</div>
<p>Neste exemplo, o método padrão <a class="reference internal" href="../reference/datamodel.html#object.__init__" title="object.__init__"><tt class="xref py py-meth docutils literal"><span class="pre">__init__()</span></tt></a> da classe <tt class="xref py py-class docutils literal"><span class="pre">Exception</span></tt>
foi redefinido. O novo comportamento simplesmente cria o atributo <em>valor</em>.
Isso substitui o comportamento padrão de criar o atributo <em>args</em>.</p>
<p>Classes de exceções podem ser definidas para fazer qualquer coisa que
qualquer outra classe faz, mas em geral são bem simples, frequentemente
oferecendo apenas alguns atributos que fornecem informações sobre o erro que
ocorreu. Ao criar um módulo que pode gerar diversos erros, uma prática comum é
criar uma classe base para as exceções definidas por aquele módulo, e as
classes específicas para cada condição de erro como subclasses dela:</p>
<div class="highlight-python"><div class="highlight"><pre><span class="k">class</span> <span class="nc">Error</span><span class="p">(</span><span class="ne">Exception</span><span class="p">):</span>
    <span class="sd">&quot;&quot;&quot;Classe base para exceções dessa módulo&quot;&quot;&quot;</span>
    <span class="k">pass</span>

<span class="k">class</span> <span class="nc">InputError</span><span class="p">(</span><span class="n">Error</span><span class="p">):</span>
    <span class="sd">&quot;&quot;&quot;Exceções levantadas por erros na entrada</span>

<span class="sd">    Atributos:</span>
<span class="sd">        expr -- expressão da entrada onde o erro ocorreu</span>
<span class="sd">        msg  -- explicação do erro</span>
<span class="sd">    &quot;&quot;&quot;</span>

    <span class="k">def</span> <span class="nf">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">expr</span><span class="p">,</span> <span class="n">msg</span><span class="p">):</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">expr</span> <span class="o">=</span> <span class="n">expr</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">msg</span> <span class="o">=</span> <span class="n">msg</span>

<span class="k">class</span> <span class="nc">TransitionError</span><span class="p">(</span><span class="n">Error</span><span class="p">):</span>
    <span class="sd">&quot;&quot;&quot;Levantada quando uma operação tenta fazer uma transição de estado não</span>
<span class="sd">    permitida.</span>

<span class="sd">    Atributos:</span>
<span class="sd">        anterior -- estado do início da transição</span>
<span class="sd">        proximo -- novo estado</span>
<span class="sd">        msg  -- explicação do porquê a transação específica não é permitida</span>
<span class="sd">    &quot;&quot;&quot;</span>

    <span class="k">def</span> <span class="nf">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">anterior</span><span class="p">,</span> <span class="n">proximo</span><span class="p">,</span> <span class="n">msg</span><span class="p">):</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">anterior</span> <span class="o">=</span> <span class="n">anterior</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">proximo</span> <span class="o">=</span> <span class="n">proximo</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">msg</span> <span class="o">=</span> <span class="n">msg</span>
</pre></div>
</div>
<p>É comum que novas exceções sejam definidas com nomes terminando em &#8220;Error&#8221;,
semelhante a muitas exceções embutidas.</p>
<p>Muitos módulos padrão definem novas exceções para reportar erros que ocorrem
no interior das funções que definem. Mais informações sobre classes aparecem
no capítulo <a class="reference internal" href="classes.html#tut-classes"><em>Classes</em></a>.</p>
</div>
<div class="section" id="definindo-acoes-de-limpeza">
<span id="tut-cleanup"></span><h2>8.6. Definindo ações de limpeza<a class="headerlink" href="#definindo-acoes-de-limpeza" title="Permalink to this headline">¶</a></h2>
<p>A instrução <a class="reference internal" href="../reference/compound_stmts.html#try"><tt class="xref std std-keyword docutils literal"><span class="pre">try</span></tt></a> possui outra cláusula opcional, cuja finalidade é
permitir a implementação de ações de limpeza, que sempre devem ser executadas
independentemente da ocorrência de exceções. Como no exemplo:</p>
<div class="highlight-python"><div class="highlight"><pre><span class="gp">&gt;&gt;&gt; </span><span class="k">try</span><span class="p">:</span>
<span class="gp">... </span>    <span class="k">raise</span> <span class="ne">KeyboardInterrupt</span>
<span class="gp">... </span><span class="k">finally</span><span class="p">:</span>
<span class="gp">... </span>    <span class="k">print</span> <span class="s">&#39;Adeus, mundo!&#39;</span>
<span class="gp">...</span>
<span class="go">Adeus, mundo!</span>
<span class="nc">KeyboardInterrupt</span>
</pre></div>
</div>
<p>Uma <em>cláusula finally</em> é sempre executada, ocorrendo ou não uma exceção.
Quando ocorre uma exceção na cláusula <a class="reference internal" href="../reference/compound_stmts.html#try"><tt class="xref std std-keyword docutils literal"><span class="pre">try</span></tt></a> e ela não é tratada por
uma cláusula <a class="reference internal" href="../reference/compound_stmts.html#except"><tt class="xref std std-keyword docutils literal"><span class="pre">except</span></tt></a> (ou quando ocorre em cláusulas
<a class="reference internal" href="../reference/compound_stmts.html#except"><tt class="xref std std-keyword docutils literal"><span class="pre">except</span></tt></a> ou <a class="reference internal" href="../reference/compound_stmts.html#else"><tt class="xref std std-keyword docutils literal"><span class="pre">else</span></tt></a>), ela é re-levantada depois que a
cláusula <a class="reference internal" href="../reference/compound_stmts.html#finally"><tt class="xref std std-keyword docutils literal"><span class="pre">finally</span></tt></a> é executada. A cláusula <a class="reference internal" href="../reference/compound_stmts.html#finally"><tt class="xref std std-keyword docutils literal"><span class="pre">finally</span></tt></a> é
executada &#8220;na saída&#8221; quando qualquer outra cláusula da instrução
<a class="reference internal" href="../reference/compound_stmts.html#try"><tt class="xref std std-keyword docutils literal"><span class="pre">try</span></tt></a> é finalizada, mesmo que seja por meio de qualquer uma das
instruções <a class="reference internal" href="../reference/simple_stmts.html#break"><tt class="xref std std-keyword docutils literal"><span class="pre">break</span></tt></a>, <a class="reference internal" href="../reference/simple_stmts.html#continue"><tt class="xref std std-keyword docutils literal"><span class="pre">continue</span></tt></a> ou <a class="reference internal" href="../reference/simple_stmts.html#return"><tt class="xref std std-keyword docutils literal"><span class="pre">return</span></tt></a>. Um
exemplo mais completo:</p>
<div class="highlight-python"><div class="highlight"><pre><span class="gp">&gt;&gt;&gt; </span><span class="k">def</span> <span class="nf">divide</span><span class="p">(</span><span class="n">x</span><span class="p">,</span> <span class="n">y</span><span class="p">):</span>
<span class="gp">... </span>    <span class="k">try</span><span class="p">:</span>
<span class="gp">... </span>        <span class="n">resultado</span> <span class="o">=</span> <span class="n">x</span> <span class="o">/</span> <span class="n">y</span>
<span class="gp">... </span>    <span class="k">except</span> <span class="ne">ZeroDivisionError</span><span class="p">:</span>
<span class="gp">... </span>        <span class="k">print</span> <span class="s">&quot;divisão por zero!&quot;</span>
<span class="gp">... </span>    <span class="k">else</span><span class="p">:</span>
<span class="gp">... </span>        <span class="k">print</span> <span class="s">&quot;resultado é&quot;</span><span class="p">,</span> <span class="n">resultado</span>
<span class="gp">... </span>    <span class="k">finally</span><span class="p">:</span>
<span class="gp">... </span>        <span class="k">print</span> <span class="s">&quot;executando a cláusula finally&quot;</span>
<span class="gp">...</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">divide</span><span class="p">(</span><span class="mi">2</span><span class="p">,</span> <span class="mi">1</span><span class="p">)</span>
<span class="go">resultado é 2</span>
<span class="go">executando a cláusula finally</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">divide</span><span class="p">(</span><span class="mi">2</span><span class="p">,</span> <span class="mi">0</span><span class="p">)</span>
<span class="go">divisão por zero!</span>
<span class="go">executando a cláusula finally</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">divide</span><span class="p">(</span><span class="s">&quot;2&quot;</span><span class="p">,</span> <span class="s">&quot;1&quot;</span><span class="p">)</span>
<span class="go">executando a cláusula finally</span>
<span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;&lt;stdin&gt;&quot;</span>, line <span class="m">1</span>, in <span class="n-Identifier">?</span>
  File <span class="nb">&quot;&lt;stdin&gt;&quot;</span>, line <span class="m">3</span>, in <span class="n-Identifier">divide</span>
<span class="nc">TypeError: unsupported operand type(s) for /</span>: <span class="n-Identifier">&#39;str&#39; and &#39;str&#39;</span>
</pre></div>
</div>
<p>Como você pode ver, a cláusula <a class="reference internal" href="../reference/compound_stmts.html#finally"><tt class="xref std std-keyword docutils literal"><span class="pre">finally</span></tt></a> é executado em todos os
casos. A exceção <a class="reference internal" href="../library/exceptions.html#exceptions.TypeError" title="exceptions.TypeError"><tt class="xref py py-exc docutils literal"><span class="pre">TypeError</span></tt></a> levantada pela divisão de duas strings não é
tratada pela cláusula <a class="reference internal" href="../reference/compound_stmts.html#except"><tt class="xref std std-keyword docutils literal"><span class="pre">except</span></tt></a> e portanto é re-levantada depois que a
cláusula <a class="reference internal" href="../reference/compound_stmts.html#finally"><tt class="xref std std-keyword docutils literal"><span class="pre">finally</span></tt></a> é executada.</p>
<p>Em aplicação do mundo real, a cláusula <a class="reference internal" href="../reference/compound_stmts.html#finally"><tt class="xref std std-keyword docutils literal"><span class="pre">finally</span></tt></a> é útil para liberar
recursos externos (como arquivos ou conexões de rede), independentemente do
uso do recurso ter sido bem sucedido ou não.</p>
</div>
<div class="section" id="acoes-de-limpeza-predefinidas">
<span id="tut-cleanup-with"></span><h2>8.7. Ações de limpeza predefinidas<a class="headerlink" href="#acoes-de-limpeza-predefinidas" title="Permalink to this headline">¶</a></h2>
<p>Alguns objetos definem ações de limpeza padrões para serem executadas quando o
objeto não é mais necessário, independentemente da operação que estava usando
o objeto ter sido ou não bem sucedida. Veja o exemplo a seguir, que tenta
abrir um arquivo e exibir seu conteúdo na tela.</p>
<div class="highlight-python"><div class="highlight"><pre><span class="k">for</span> <span class="n">linha</span> <span class="ow">in</span> <span class="nb">open</span><span class="p">(</span><span class="s">&quot;meuarquivo.txt&quot;</span><span class="p">):</span>
    <span class="k">print</span> <span class="n">linha</span>
</pre></div>
</div>
<p>O problema com esse código é que ele deixa o arquivo aberto um período
indeterminado depois que o código é executado. Isso não chega a ser problema
em scripts simples, mas pode ser um problema para grandes aplicações. A
palavra reservada <a class="reference internal" href="../reference/compound_stmts.html#with"><tt class="xref std std-keyword docutils literal"><span class="pre">with</span></tt></a> permite que objetos como arquivos sejam
utilizados com a certeza de que sempre serão prontamente e corretamente
finalizados.</p>
<div class="highlight-python"><div class="highlight"><pre><span class="k">with</span> <span class="nb">open</span><span class="p">(</span><span class="s">&quot;meuarquivo.txt&quot;</span><span class="p">)</span> <span class="k">as</span> <span class="n">a</span><span class="p">:</span>
    <span class="k">for</span> <span class="n">linha</span> <span class="ow">in</span> <span class="n">a</span><span class="p">:</span>
        <span class="k">print</span> <span class="n">linha</span>
</pre></div>
</div>
<p>Depois que a instrução é executada, o arquivo <em>a</em> é sempre fechado, mesmo se
ocorrer um problema durante o processamento das linhas. Outros objetos que
fornecem ações de limpeza predefinidas as indicarão em suas documentações.</p>
</div>
</div>


          </div>
        </div>
      </div>
      <div class="sphinxsidebar">
        <div class="sphinxsidebarwrapper">
  <h3><a href="../contents.html">Table Of Contents</a></h3>
  <ul>
<li><a class="reference internal" href="#">8. Erros e exceções</a><ul>
<li><a class="reference internal" href="#erros-de-sintaxe">8.1. Erros de sintaxe</a></li>
<li><a class="reference internal" href="#excecoes">8.2. Exceções</a></li>
<li><a class="reference internal" href="#tratamento-de-excecoes">8.3. Tratamento de exceções</a></li>
<li><a class="reference internal" href="#levantando-excecoes">8.4. Levantando exceções</a></li>
<li><a class="reference internal" href="#excecoes-definidas-pelo-usuario">8.5. Exceções definidas pelo usuário</a></li>
<li><a class="reference internal" href="#definindo-acoes-de-limpeza">8.6. Definindo ações de limpeza</a></li>
<li><a class="reference internal" href="#acoes-de-limpeza-predefinidas">8.7. Ações de limpeza predefinidas</a></li>
</ul>
</li>
</ul>

  <h4>Previous topic</h4>
  <p class="topless"><a href="inputoutput.html"
                        title="previous chapter">7. Entrada e saída</a></p>
  <h4>Next topic</h4>
  <p class="topless"><a href="classes.html"
                        title="next chapter">9. Classes</a></p>
<h3>This Page</h3>
<ul class="this-page-menu">
  <li><a href="../bugs.html">Report a Bug</a></li>
  <li><a href="../_sources/tutorial/errors.txt"
         rel="nofollow">Show Source</a></li>
</ul>

<div id="searchbox" style="display: none">
  <h3>Quick search</h3>
    <form class="search" action="../search.html" method="get">
      <input type="text" name="q" size="18" />
      <input type="submit" value="Go" />
      <input type="hidden" name="check_keywords" value="yes" />
      <input type="hidden" name="area" value="default" />
    </form>
    <p class="searchtip" style="font-size: 90%">
    Enter search terms or a module, class or function name.
    </p>
</div>
<script type="text/javascript">$('#searchbox').show(0);</script>
        </div>
      </div>
      <div class="clearer"></div>
    </div>
    <div class="related">
      <h3>Navigation</h3>
      <ul>
        <li class="right" style="margin-right: 10px">
          <a href="../genindex.html" title="General Index"
             >index</a></li>
        <li class="right" >
          <a href="../py-modindex.html" title="Python Module Index"
             >modules</a> |</li>
        <li class="right" >
          <a href="classes.html" title="9. Classes"
             >next</a> |</li>
        <li class="right" >
          <a href="inputoutput.html" title="7. Entrada e saída"
             >previous</a> |</li>
        <li><img src="../_static/py.png" alt=""
                 style="vertical-align: middle; margin-top: -1px"/></li>
        <li><a href="../index.html">Python v2.7.2 documentation</a> &raquo;</li>

          <li><a href="index.html" >O tutorial de Python</a> &raquo;</li> 
      </ul>
    </div>
    <div class="footer">
    &copy; <a href="../copyright.html">Copyright</a> 1990-2012, Python Software Foundation.
    <br />
    The Python Software Foundation is a non-profit corporation.  
    <a href="http://www.python.org/psf/donations/">Please donate.</a>
    <br />
    Last updated on Apr 03, 2012.
    <a href="../bugs.html">Found a bug</a>?
    <br />
    Created using <a href="http://sphinx.pocoo.org/">Sphinx</a> 1.0.7.
    </div>

  </body>
</html>